### ISSUE TITLE
Some first issues with Compose foundation implementation

### ISSUE THREAD

**Issue by luongvo** [thawzintoe-ptut/Insightify#13]
Hi again here 👋 

First of all, you did well to include the necessary features & requirements. There are some plus points:
- Modular + feature bundles.
- Managing project dependencies via TOML.
- Caching integrated.
- Has the Home's skeleton loading.

Here are some first issues with Compose foundation implementation that I found from the code base:
- I think forcing to set `Scaffold` at the root which wraps the app navigation is not a great idea. We might need to integrate the nav graph with non-Scaffold screens or views. Forcing this could cause issues later. Should we move `Scaffold` to screen levels? https://github.com/thawzintoe-ptut/Insightify/blob/f8445342b47177e4964c5fa8cff57960f4dc9c77/app/src/main/java/com/ptut/insightify/MainActivity.kt#L33-L40
- You did not seem to apply using the [`Preview` function](https://developer.android.com/develop/ui/compose/tooling/previews) to preview Composable components: screen, view, etc. Do you think it's good to always have them in Compose? Why and why not?
- Why do we need a custom `BackHandler` here? What happens without it? https://github.com/thawzintoe-ptut/Insightify/blob/f8445342b47177e4964c5fa8cff57960f4dc9c77/app/src/main/java/com/ptut/insightify/MainActivity.kt#L31
- The way to provide ViewModel from Hilt does not seem to be consistent. Should we define these viewModel as a Composable function parameter with the default value `viewModel: HomeViewModel = hiltViewModel()`?
	- MainViewModel: a local val from the nav graph https://github.com/thawzintoe-ptut/Insightify/blob/f8445342b47177e4964c5fa8cff57960f4dc9c77/app/src/main/java/com/ptut/insightify/navigation/NavControllerExt.kt#L20-L24
	- LoginScreen: passing param from the nav graph https://github.com/thawzintoe-ptut/Insightify/blob/f8445342b47177e4964c5fa8cff57960f4dc9c77/feature/auth/src/main/java/com/ptut/insightify/auth/navigation/LoginNavigation.kt#L12-L13
	- HomeScreen: passing param from the nav graph https://github.com/thawzintoe-ptut/Insightify/blob/f8445342b47177e4964c5fa8cff57960f4dc9c77/feature/home/src/main/java/com/ptut/insightify/home/navigation/HomeNavigation.kt#L16-L17
- There are some unnecessary public Composable definitions from the code base, e.g., https://github.com/thawzintoe-ptut/Insightify/blob/f8445342b47177e4964c5fa8cff57960f4dc9c77/feature/auth/src/main/java/com/ptut/insightify/auth/LoginScreen.kt#L186-L309

**Comment by thawzintoe-ptut** [comment]
Could you please review it again @luongvo
