### ISSUE TITLE
Some broken UI issues

### ISSUE THREAD

**Issue by luongvo** [thawzintoe-ptut/Insightify#15]
- Login screen

	- Background
		![image](https://github.com/thawzintoe-ptut/Insightify/assets/16315358/4f0d05c6-2b37-439e-a75b-2f7b24e5ffa8)

	- Keyboard is overlapping the content
		![image](https://github.com/thawzintoe-ptut/Insightify/assets/16315358/62fd1b95-9049-4941-8c8c-ef6b701c3be1)

	- I do not seem to be able to switch to the email input if an error occurs. 
		
		https://github.com/thawzintoe-ptut/Insightify/assets/16315358/7ccd0fb7-2824-436a-9d8c-51b3215e720a

**Comment by thawzintoe-ptut** [comment]
I think I might be `edgetoedge` issue with material theme. I will fix it as soon as possible
